export const agentUsage = {
  codex: {
    id: 'codex',
    label: 'Codex',
    provider: 'OpenAI',
    fiveHour: {
      window: '5h',
      label: '5時間',
      reset: 'あと 2時間14分',
      usedPercent: 32,
      remainingPercent: 68,
    },
    sevenDay: {
      window: '7d',
      label: '7日間',
      reset: '月曜 09:00 にリセット',
      usedPercent: 64,
      remainingPercent: 36,
    },
  },
  claudeCode: {
    id: 'claude-code',
    label: 'Claude Code',
    provider: 'Anthropic',
    fiveHour: {
      window: '5h',
      label: '5時間',
      reset: 'あと 1時間08分',
      usedPercent: 61,
      remainingPercent: 39,
    },
    sevenDay: {
      window: '7d',
      label: '7日間',
      reset: '水曜 14:30 にリセット',
      usedPercent: 47,
      remainingPercent: 53,
    },
  },
  opencode: {
    id: 'opencode',
    label: 'OpenCode',
    provider: 'OpenCode',
    fiveHour: {
      window: '5h',
      label: '5時間',
      reset: 'あと 4時間02分',
      usedPercent: 16,
      remainingPercent: 84,
    },
    sevenDay: {
      window: '7d',
      label: '7日間',
      reset: '日曜 23:00 にリセット',
      usedPercent: 22,
      remainingPercent: 78,
    },
  },
};

export const activityThreads = [
  {
    id: 'thread-codex-workspace',
    agent: 'codex',
    agentLabel: 'Codex',
    title: 'ワークスペースのレイアウトを確認',
    status: 'running',
    statusLabel: '実行中',
    project: 'clair',
    projectId: 'clair',
    terminalId: 'clair-terminal',
    summary: 'clair のエディタとターミナル配置を確認しています',
    updatedAt: 'たった今',
    messages: [
      {
        id: 'message-codex-workspace-1',
        role: 'user',
        content: 'プロジェクトを切り替えても、エディタとターミナルの配置を復元できるようにして。',
        timestamp: '09:42',
      },
      {
        id: 'message-codex-workspace-2',
        role: 'assistant',
        content: 'clair の保存済みレイアウトを読み込みました。現在はエディタの右側にターミナルを表示しています。',
        timestamp: '09:43',
      },
      {
        id: 'message-codex-workspace-3',
        role: 'assistant',
        content: '次に WorkspaceView の復元テストを実行し、プロジェクト切り替え時の状態を確認します。',
        timestamp: '09:44',
      },
    ],
  },
  {
    id: 'thread-codex-debug',
    agent: 'codex',
    agentLabel: 'Codex',
    title: '復元テストの失敗箇所を調査',
    status: 'waiting',
    statusLabel: '入力待ち',
    project: 'ccedit',
    projectId: 'ccedit',
    terminalId: 'ccedit-terminal',
    summary: 'WorkspaceRestoreTests の結果を待っています',
    updatedAt: '6分前',
    messages: [
      {
        id: 'message-codex-debug-1',
        role: 'user',
        content: '保存した terminalPercent が次回起動時に丸められてしまう原因を見て。',
        timestamp: '09:36',
      },
      {
        id: 'message-codex-debug-2',
        role: 'assistant',
        content: 'ccedit の ProjectLayout.restore() までは値が保持されています。UI 側の境界値補正を確認します。',
        timestamp: '09:37',
      },
      {
        id: 'message-codex-debug-3',
        role: 'assistant',
        content: '候補を2つ見つけました。再現条件を確認できたら修正案を適用します。',
        timestamp: '09:38',
      },
    ],
  },
  {
    id: 'thread-claude-editor',
    agent: 'claude-code',
    agentLabel: 'Claude Code',
    title: 'エディタの余白と行間を整える',
    status: 'waiting',
    statusLabel: '実行中',
    project: 'ccedit',
    projectId: 'ccedit',
    terminalId: 'ccedit-terminal',
    summary: '変更を適用する前に承認が必要です',
    updatedAt: '2分前',
    messages: [
      {
        id: 'message-claude-editor-1',
        role: 'user',
        content: 'コードの可読性を優先して、行間と左右の余白を少し広げてください。',
        timestamp: '09:40',
      },
      {
        id: 'message-claude-editor-2',
        role: 'assistant',
        content: 'EditorPane の本文幅を確認しました。フォントサイズを保ったまま、ガターと本文の間隔を調整します。',
        timestamp: '09:41',
      },
      {
        id: 'message-claude-editor-3',
        role: 'assistant',
        content: '変更案を準備しました。既存の One Dark の階調を保ったまま、適用前に確認をお願いします。',
        timestamp: '09:42',
      },
    ],
    approval: {
      id: 'approval-claude-editor',
      tool: 'Bash',
      title: '変更を適用してテストを実行しますか？',
      command: 'git diff --check && swift test --package-path packages/ClairMobileKit',
      cwd: '~/Projects/ccedit',
      reason: 'Claude Codeがワークツリーを検証し、変更後のテストを実行しようとしています。',
      risk: 'ローカルのテストコマンドを実行',
    },
  },
  {
    id: 'thread-claude-release',
    agent: 'claude-code',
    agentLabel: 'Claude Code',
    title: 'リリースノートを整理',
    status: 'completed',
    statusLabel: '完了',
    project: 'clair-releases',
    projectId: 'clair-releases',
    terminalId: 'releases-terminal',
    summary: '次回リリースの変更点を README に反映しました',
    updatedAt: '18分前',
    messages: [
      {
        id: 'message-claude-release-1',
        role: 'user',
        content: '次回リリースに含めるエディタとデバッグ機能の変更点をまとめて。',
        timestamp: '09:20',
      },
      {
        id: 'message-claude-release-2',
        role: 'assistant',
        content: 'clair-releases の既存フォーマットに合わせて、エディタ、ターミナル、デバッグの3項目に整理します。',
        timestamp: '09:22',
      },
      {
        id: 'message-claude-release-3',
        role: 'assistant',
        content: 'README.md を更新しました。変更内容の確認が終わったので、このセッションを終了します。',
        timestamp: '09:24',
      },
    ],
  },
  {
    id: 'thread-opencode-graph',
    agent: 'opencode',
    agentLabel: 'OpenCode',
    title: 'Swift の依存関係を可視化',
    status: 'waiting',
    statusLabel: '入力待ち',
    project: 'clair',
    projectId: 'clair',
    terminalId: 'clair-terminal',
    summary: 'WorkspaceView から参照される Swift ファイルを解析しました',
    updatedAt: '11分前',
    messages: [
      {
        id: 'message-opencode-graph-1',
        role: 'user',
        content: 'WorkspaceView から EditorPane までの依存関係をグラフで見たい。',
        timestamp: '09:31',
      },
      {
        id: 'message-opencode-graph-2',
        role: 'assistant',
        content: 'clair の Swift ファイルを解析し、View、SourceEditorView、ProjectLayout の関係を抽出しました。',
        timestamp: '09:33',
      },
      {
        id: 'message-opencode-graph-3',
        role: 'assistant',
        content: 'グラフを表示できます。特定のシンボルを選択すると、参照元と参照先を絞り込めます。',
        timestamp: '09:34',
      },
    ],
  },
  {
    id: 'thread-opencode-release-check',
    agent: 'opencode',
    agentLabel: 'OpenCode',
    title: 'リリース前の変更を確認',
    status: 'completed',
    statusLabel: '完了',
    project: 'clair-releases',
    projectId: 'clair-releases',
    terminalId: 'releases-terminal',
    summary: 'main との差分に未確認の変更はありません',
    updatedAt: '27分前',
    messages: [
      {
        id: 'message-opencode-release-1',
        role: 'user',
        content: 'リリースブランチに取り込む前に、main との差分を確認してください。',
        timestamp: '09:04',
      },
      {
        id: 'message-opencode-release-2',
        role: 'assistant',
        content: 'clair-releases の差分を確認しました。変更はリリースノートとバージョン情報に限定されています。',
        timestamp: '09:07',
      },
      {
        id: 'message-opencode-release-3',
        role: 'assistant',
        content: '検査を完了しました。追加のコンフリクトは見つかりませんでした。',
        timestamp: '09:08',
      },
    ],
  },
];

export const settingsSections = [
  {
    id: 'general',
    label: '一般',
    description: 'ワークスペースの基本動作とアプリ全体の表示を設定します。',
    items: [
      {
        id: 'language',
        label: '表示言語',
        description: 'Clair のメニューと補助テキストに使用する言語です。',
        type: 'select',
        defaultValue: 'ja-JP',
        options: [
          { value: 'ja-JP', label: '日本語' },
          { value: 'en-US', label: '英語' },
        ],
      },
      {
        id: 'theme',
        label: '外観',
        description: 'エディタとサイドバーに適用するカラーテーマです。',
        type: 'select',
        defaultValue: 'one-dark',
        options: [
          { value: 'one-dark', label: 'One Dark' },
          { value: 'system', label: 'システムに合わせる' },
          { value: 'light', label: 'ライト' },
        ],
      },
      {
        id: 'show-usage-footer',
        label: '使用量をフッターに表示',
        description: '各エージェントの5時間・7日間の残り使用量を常に表示します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'confirm-close',
        label: '実行中のセッションを閉じる前に確認',
        description: 'エージェントやターミナルが実行中の場合に確認を表示します。',
        type: 'toggle',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'ai-providers',
    label: 'AIプロバイダー',
    description: 'エージェントの既定値、モデル、接続先を管理します。',
    items: [
      {
        id: 'default-agent',
        label: '既定のエージェント',
        description: '新しいターミナルを開いたときに選択されるエージェントです。',
        type: 'select',
        defaultValue: 'codex',
        options: [
          { value: 'codex', label: 'Codex' },
          { value: 'claude-code', label: 'Claude Code' },
          { value: 'opencode', label: 'OpenCode' },
        ],
      },
      {
        id: 'codex-model',
        label: 'Codex モデル',
        description: 'Codex セッションで優先して使用するモデルです。',
        type: 'select',
        defaultValue: 'gpt-5.6',
        options: [
          { value: 'gpt-5.6', label: 'GPT-5.6' },
          { value: 'gpt-5.5', label: 'GPT-5.5' },
        ],
      },
      {
        id: 'claude-code-command',
        label: 'Claude Code のコマンド',
        description: 'ターミナルから Claude Code を起動するときのコマンドです。',
        type: 'text',
        defaultValue: 'claude',
      },
      {
        id: 'opencode-command',
        label: 'OpenCode のコマンド',
        description: 'ターミナルから OpenCode を起動するときのコマンドです。',
        type: 'text',
        defaultValue: 'opencode',
      },
      {
        id: 'show-rate-limits',
        label: 'レート制限を表示',
        description: 'エージェントごとの使用量ポップオーバーを有効にします。',
        type: 'toggle',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'editor',
    label: 'エディタ',
    description: 'コードの編集、検索、差分表示に関する設定です。',
    items: [
      {
        id: 'font-size',
        label: 'フォントサイズ',
        description: 'ソースコードと差分ビューで使用する文字サイズです。',
        type: 'number',
        defaultValue: 15,
        min: 12,
        max: 24,
        step: 1,
      },
      {
        id: 'line-height',
        label: '行間',
        description: 'コードの行同士の間隔です。',
        type: 'number',
        defaultValue: 1.8,
        min: 1.2,
        max: 2.4,
        step: 0.1,
      },
      {
        id: 'word-wrap',
        label: '行の折り返し',
        description: '長い行をエディタの幅に合わせて折り返します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'show-minimap',
        label: 'ミニマップを表示',
        description: 'ファイル全体の縮小プレビューを右端に表示します。',
        type: 'toggle',
        defaultValue: false,
      },
      {
        id: 'format-on-save',
        label: '保存時にフォーマット',
        description: '保存時に選択中の言語フォーマッターを実行します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'inline-diff',
        label: 'インライン差分を表示',
        description: '変更された行の横に追加・削除の情報を表示します。',
        type: 'toggle',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'terminal',
    label: 'ターミナル',
    description: 'ターミナルの配置、シェル、セッションの扱いを設定します。',
    items: [
      {
        id: 'default-shell',
        label: '既定のシェル',
        description: '新しく作成するターミナルで使用するシェルです。',
        type: 'select',
        defaultValue: 'claude',
        options: [
          { value: 'claude', label: 'Claude Code' },
          { value: 'zsh', label: 'zsh' },
          { value: 'opencode', label: 'OpenCode' },
        ],
      },
      {
        id: 'panel-position',
        label: 'パネルの位置',
        description: 'ターミナルをエディタの下または右に表示します。',
        type: 'select',
        defaultValue: 'right',
        options: [
          { value: 'right', label: '右' },
          { value: 'bottom', label: '下' },
        ],
      },
      {
        id: 'terminal-font-size',
        label: 'フォントサイズ',
        description: 'ターミナル本文で使用する文字サイズです。',
        type: 'number',
        defaultValue: 13,
        min: 11,
        max: 20,
        step: 1,
      },
      {
        id: 'preserve-sessions',
        label: 'セッションを保持',
        description: 'プロジェクトを切り替えてもターミナルの状態を保持します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'confirm-destructive-commands',
        label: '破壊的なコマンドを確認',
        description: '削除や強制上書きを行うコマンドの前に確認を表示します。',
        type: 'toggle',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'mobile',
    label: 'モバイル',
    description: 'モバイル端末からワークスペースへ接続するための設定です。',
    items: [
      {
        id: 'mobile-connection',
        label: 'モバイル接続',
        description: 'ペアリング済みの端末からアクティビティと通知を受け取ります。',
        type: 'toggle',
        defaultValue: false,
      },
      {
        id: 'device-name',
        label: '接続先の表示名',
        description: 'モバイルアプリに表示する、このワークスペースの名前です。',
        type: 'text',
        defaultValue: 'Daiki の Clair',
      },
      {
        id: 'pair-mobile-device',
        label: 'モバイル端末を接続',
        description: 'QRコードまたは6桁のコードを使って端末をペアリングします。',
        type: 'button',
        defaultValue: '接続コードを表示',
        action: 'pair-mobile-device',
      },
      {
        id: 'mobile-notifications',
        label: '通知を同期',
        description: 'エージェントの完了や入力待ちをモバイルに通知します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'mobile-cellular',
        label: 'モバイルデータ通信を許可',
        description: 'Wi-Fi 接続がない場合も同期を続けます。',
        type: 'toggle',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'updates',
    label: 'アップデート',
    description: 'Clair とエージェント連携の更新を確認します。',
    items: [
      {
        id: 'automatic-update-checks',
        label: 'アップデートを自動確認',
        description: '起動時と1日1回、利用可能な更新を確認します。',
        type: 'toggle',
        defaultValue: true,
      },
      {
        id: 'update-channel',
        label: '更新チャンネル',
        description: '安定版または先行版の更新を受け取ります。',
        type: 'select',
        defaultValue: 'stable',
        options: [
          { value: 'stable', label: '安定版' },
          { value: 'preview', label: 'プレビュー版' },
        ],
      },
      {
        id: 'check-for-updates',
        label: 'アップデートを確認',
        description: '今すぐ最新バージョンを確認し、結果を通知します。',
        type: 'button',
        defaultValue: '確認する',
        action: 'show-update-toast',
      },
      {
        id: 'include-agent-previews',
        label: 'エージェントの先行更新を含める',
        description: 'Codex、Claude Code、OpenCode のプレビュー版を対象にします。',
        type: 'toggle',
        defaultValue: false,
      },
      {
        id: 'last-update-check',
        label: '最後の確認',
        description: 'Clair が最後に更新を確認した時刻です。',
        type: 'status',
        defaultValue: '今日 09:12',
      },
    ],
  },
];

export const branchDiffs = {
  main: {
    branch: 'main',
    baseBranch: 'main~1',
    compareBranch: 'main',
    project: 'clair',
    summary: {
      filesChanged: 2,
      additions: 8,
      deletions: 3,
    },
    files: [
      {
        project: 'clair',
        path: 'App/WorkspaceView.swift',
        status: 'modified',
        additions: 5,
        deletions: 2,
        hunks: [
          {
            header: '@@ -4,8 +4,11 @@ struct WorkspaceView: View',
            lines: [
              {
                kind: 'context',
                left: { line: 4, text: 'struct WorkspaceView: View {' },
                right: { line: 4, text: 'struct WorkspaceView: View {' },
              },
              {
                kind: 'remove',
                left: { line: 5, text: '    let workspace: Workspace' },
                right: null,
              },
              {
                kind: 'add',
                left: null,
                right: { line: 5, text: '    @Environment(\\.workspace) private var workspace' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 6, text: '    @State private var selectedFile: SourceDocument.ID?' },
              },
              {
                kind: 'context',
                left: { line: 6, text: '' },
                right: { line: 7, text: '' },
              },
              {
                kind: 'context',
                left: { line: 7, text: '    var body: some View {' },
                right: { line: 8, text: '    var body: some View {' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 9, text: '        WorkspaceContent(selection: $selectedFile)' },
              },
              {
                kind: 'context',
                left: { line: 8, text: '        NavigationSplitView {' },
                right: { line: 10, text: '        NavigationSplitView {' },
              },
            ],
          },
        ],
      },
      {
        project: 'clair',
        path: 'Tests/WorkspaceRestoreTests.swift',
        status: 'added',
        additions: 3,
        deletions: 0,
        hunks: [
          {
            header: '@@ -0,0 +1,3 @@',
            lines: [
              {
                kind: 'add',
                left: null,
                right: { line: 1, text: 'import Testing' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 2, text: '@testable import Clair' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 3, text: '@Test func restoresProjectLayout() { #expect(ProjectLayout.restore().terminalPosition == .right) }' },
              },
            ],
          },
        ],
      },
    ],
  },
  'feature/editor-polish': {
    branch: 'feature/editor-polish',
    baseBranch: 'main',
    compareBranch: 'feature/editor-polish',
    project: 'ccedit',
    summary: {
      filesChanged: 3,
      additions: 16,
      deletions: 6,
    },
    files: [
      {
        project: 'clair',
        path: 'App/EditorPane.swift',
        status: 'modified',
        additions: 7,
        deletions: 3,
        hunks: [
          {
            header: '@@ -5,10 +5,14 @@ struct EditorPane: NSViewRepresentable',
            lines: [
              {
                kind: 'context',
                left: { line: 5, text: '    let document: SourceDocument' },
                right: { line: 5, text: '    let document: SourceDocument' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 6, text: '    @Binding var selectedRange: NSRange?' },
              },
              {
                kind: 'context',
                left: { line: 6, text: '' },
                right: { line: 7, text: '' },
              },
              {
                kind: 'remove',
                left: { line: 7, text: '    func makeNSView(context: Context) -> SourceEditorView {' },
                right: null,
              },
              {
                kind: 'add',
                left: null,
                right: { line: 8, text: '    func makeNSView(context: Context) -> SourceEditorView {' },
              },
              {
                kind: 'remove',
                left: { line: 8, text: '        SourceEditorView(document: document)' },
                right: null,
              },
              {
                kind: 'add',
                left: null,
                right: { line: 9, text: '        let view = SourceEditorView(document: document)' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 10, text: '        view.restoreSelection(selectedRange)' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 11, text: '        return view' },
              },
              {
                kind: 'context',
                left: { line: 9, text: '    }' },
                right: { line: 12, text: '    }' },
              },
            ],
          },
        ],
      },
      {
        project: 'ccedit',
        path: 'src/components/EditorPane.tsx',
        status: 'modified',
        additions: 6,
        deletions: 2,
        hunks: [
          {
            header: '@@ -18,7 +18,11 @@ export function EditorPane',
            lines: [
              {
                kind: 'context',
                left: { line: 18, text: '  const [isDirty, setIsDirty] = useState(false)' },
                right: { line: 18, text: '  const [isDirty, setIsDirty] = useState(false)' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 19, text: '  const [showSymbols, setShowSymbols] = useState(true)' },
              },
              {
                kind: 'remove',
                left: { line: 21, text: '  return <EditorSurface document={document} />' },
                right: null,
              },
              {
                kind: 'add',
                left: null,
                right: { line: 22, text: '  return <EditorSurface document={document} showSymbols={showSymbols} />' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 23, text: '}' },
              },
              {
                kind: 'context',
                left: { line: 22, text: '}' },
                right: { line: 24, text: '}' },
              },
            ],
          },
        ],
      },
      {
        project: 'clair',
        path: 'App/SourceGraphView.swift',
        status: 'added',
        additions: 3,
        deletions: 0,
        hunks: [
          {
            header: '@@ -0,0 +1,3 @@',
            lines: [
              {
                kind: 'add',
                left: null,
                right: { line: 1, text: 'struct SourceGraphView: View {' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 2, text: '    let graph: SourceGraph' },
              },
              {
                kind: 'add',
                left: null,
                right: { line: 3, text: '}' },
              },
            ],
          },
        ],
      },
    ],
  },
};

export const sourceGraph = {
  project: 'clair',
  title: 'Clair の Swift ソースグラフ',
  focusFile: 'App/WorkspaceView.swift',
  nodes: [
    {
      id: 'file-clair-app',
      type: 'file',
      kind: 'struct',
      label: 'ClairApp',
      file: 'App/ClairApp.swift',
      line: 4,
      project: 'clair',
    },
    {
      id: 'file-workspace-view',
      type: 'file',
      kind: 'struct',
      label: 'WorkspaceView',
      file: 'App/WorkspaceView.swift',
      line: 3,
      project: 'clair',
    },
    {
      id: 'file-file-tree',
      type: 'file',
      kind: 'view',
      label: 'FileTree',
      file: 'App/FileTree.swift',
      line: 5,
      project: 'clair',
    },
    {
      id: 'file-editor-pane',
      type: 'file',
      kind: 'representable',
      label: 'EditorPane',
      file: 'Editor/EditorPane.swift',
      line: 5,
      project: 'clair',
    },
    {
      id: 'file-source-editor',
      type: 'file',
      kind: 'view',
      label: 'SourceEditorView',
      file: 'Editor/SourceEditorView.swift',
      line: 8,
      project: 'clair',
    },
    {
      id: 'file-workspace-model',
      type: 'file',
      kind: 'model',
      label: 'Workspace',
      file: 'Model/Workspace.swift',
      line: 4,
      project: 'clair',
    },
    {
      id: 'file-project-layout',
      type: 'file',
      kind: 'model',
      label: 'ProjectLayout',
      file: 'Model/ProjectLayout.swift',
      line: 6,
      project: 'clair',
    },
    {
      id: 'file-restore-tests',
      type: 'file',
      kind: 'test',
      label: 'WorkspaceRestoreTests',
      file: 'Tests/WorkspaceRestoreTests.swift',
      line: 4,
      project: 'clair',
    },
  ],
  edges: [
    {
      id: 'edge-app-workspace',
      source: 'file-clair-app',
      target: 'file-workspace-view',
      relation: 'creates',
      label: '表示',
    },
    {
      id: 'edge-workspace-model',
      source: 'file-workspace-view',
      target: 'file-workspace-model',
      relation: 'reads',
      label: '状態を読む',
    },
    {
      id: 'edge-workspace-tree',
      source: 'file-workspace-view',
      target: 'file-file-tree',
      relation: 'renders',
      label: 'ファイルツリー',
    },
    {
      id: 'edge-workspace-editor',
      source: 'file-workspace-view',
      target: 'file-editor-pane',
      relation: 'renders',
      label: 'エディタ',
    },
    {
      id: 'edge-editor-source',
      source: 'file-editor-pane',
      target: 'file-source-editor',
      relation: 'wraps',
      label: 'ラップ',
    },
    {
      id: 'edge-workspace-layout',
      source: 'file-workspace-view',
      target: 'file-project-layout',
      relation: 'restores',
      label: '配置を復元',
    },
    {
      id: 'edge-tests-layout',
      source: 'file-restore-tests',
      target: 'file-project-layout',
      relation: 'verifies',
      label: 'テスト',
    },
    {
      id: 'edge-tests-workspace',
      source: 'file-restore-tests',
      target: 'file-workspace-view',
      relation: 'covers',
      label: 'カバレッジ',
    },
  ],
};

export const debugSteps = {
  project: 'clair',
  terminalId: 'clair-terminal',
  file: 'App/EditorPane.swift',
  sessionId: 'debug-editor-pane-01',
  status: 'paused',
  statusLabel: 'ブレークポイントで停止',
  currentStep: 2,
  breakpoint: {
    id: 'breakpoint-editor-init',
    file: 'App/EditorPane.swift',
    line: 9,
    enabled: true,
    condition: 'document.isDirty == false',
    hitCount: 1,
  },
  breakpoints: [
    {
      id: 'breakpoint-editor-init',
      file: 'App/EditorPane.swift',
      line: 9,
      enabled: true,
      condition: 'document.isDirty == false',
      hitCount: 1,
    },
    {
      id: 'breakpoint-workspace-open',
      file: 'App/WorkspaceView.swift',
      line: 12,
      enabled: true,
      condition: '',
      hitCount: 0,
    },
  ],
  stack: [
    {
      id: 'frame-0',
      frame: 0,
      function: 'EditorPane.makeNSView(context:)',
      file: 'App/EditorPane.swift',
      line: 9,
      module: 'Clair',
      selected: true,
    },
    {
      id: 'frame-1',
      frame: 1,
      function: 'WorkspaceView.body.getter',
      file: 'App/WorkspaceView.swift',
      line: 12,
      module: 'Clair',
      selected: false,
    },
    {
      id: 'frame-2',
      frame: 2,
      function: 'WindowGroup.body',
      file: 'App/ClairApp.swift',
      line: 9,
      module: 'Clair',
      selected: false,
    },
  ],
  variables: [
    {
      name: 'document',
      type: 'SourceDocument',
      value: 'SourceDocument(id: "workspace-view")',
      scope: 'local',
      changed: false,
    },
    {
      name: 'document.path',
      type: 'String',
      value: 'App/WorkspaceView.swift',
      scope: 'property',
      changed: false,
    },
    {
      name: 'document.isDirty',
      type: 'Bool',
      value: 'false',
      scope: 'property',
      changed: true,
    },
    {
      name: 'selectedRange',
      type: 'NSRange?',
      value: 'nil',
      scope: 'local',
      changed: false,
    },
    {
      name: 'workspace.project',
      type: 'Project.ID',
      value: 'clair',
      scope: 'environment',
      changed: false,
    },
  ],
  stepActions: [
    {
      id: 'continue',
      label: '続行',
      shortcut: 'F5',
      description: '次のブレークポイントまで実行します。',
      enabled: true,
    },
    {
      id: 'step-over',
      label: 'ステップオーバー',
      shortcut: 'F10',
      description: '現在の行を実行し、同じフレームで停止します。',
      enabled: true,
    },
    {
      id: 'step-into',
      label: 'ステップイン',
      shortcut: 'F11',
      description: '呼び出し先の関数に入って停止します。',
      enabled: true,
    },
    {
      id: 'step-out',
      label: 'ステップアウト',
      shortcut: 'Shift F11',
      description: '現在の関数を完了し、呼び出し元で停止します。',
      enabled: true,
    },
    {
      id: 'restart',
      label: '再起動',
      shortcut: 'Cmd R',
      description: 'デバッグセッションを最初から起動します。',
      enabled: true,
    },
    {
      id: 'stop',
      label: '停止',
      shortcut: 'Shift F5',
      description: '実行中のデバッグセッションを終了します。',
      enabled: true,
    },
  ],
  trace: [
    {
      index: 1,
      action: 'continue',
      label: 'セッションを開始',
      file: 'App/EditorPane.swift',
      line: 9,
      state: 'completed',
    },
    {
      index: 2,
      action: 'breakpoint',
      label: 'ブレークポイントで停止',
      file: 'App/EditorPane.swift',
      line: 9,
      state: 'current',
    },
    {
      index: 3,
      action: 'step-over',
      label: '選択範囲を復元',
      file: 'App/EditorPane.swift',
      line: 10,
      state: 'next',
    },
  ],
};
