// UI string tables for `tr`. Keys are the literals as written in code, interpolations as `%@`
// (use `%1$@`, `%2$@` in a value to reorder). `english` translates the Japanese-written UI;
// `japanese` translates the English-written UI (menu bar titles).

extension LocalizedStrings {
  static let english: [String: String] = [
    // Concierge (ADR-0020)
    "コンシェルジュ": "Concierge", "コンシェルジュを開く": "Open Concierge", "起動": "Start", "入力待ち": "Waiting for input",
    "終了 %@": "Exited %@", "ペイン %@ へ移動": "Go to pane %@", "Claude Code · 実行中": "Claude Code · Running",
    "未起動": "Not running", "コンシェルジュのターミナルを表示": "Show the concierge terminal", "チャットに戻る": "Back to chat",
    "担当中のタスク": "Tasks", "%@ 件実行中": "%@ running", "まだありません": "None yet", "%@ を編集": "Edit %@",
    "コンシェルジュは起動していません": "The concierge is not running",
    "依頼を送ると、ここに会話が表示されます": "Send a request and the conversation appears here",
    "コンシェルジュに頼む…": "Ask the concierge…",
    "# コンシェルジュへの指示\n\nこの Project で守ってほしいことを書きます。次回の起動から反映されます。\n":
      "# Concierge instructions\n\nWrite what the concierge should follow in this Project. Applies from its next start.\n",
    // Sections and settings
    "一般": "General", "AIプロバイダー": "AI Providers", "使用状況": "Usage", "エディタ": "Editor",
    "ターミナル": "Terminal", "モバイル": "Mobile", "アップデート": "Updates",
    "ワークスペースの基本動作とアプリ全体の表示を設定します。": "How the workspace behaves and how the app looks.",
    "依頼・追記と推定費用の集計": "Prompts, follow-ups, and estimated cost",
    "%@ の設定です。": "%@ settings.",
    "設定 · %@": "Settings · %@",
    "ワークスペース": "Workspace",
    "前回のレイアウトを復元": "Restore previous layout",
    "Projectごとのファイル、ターミナル、分割位置を再開します。": "Reopens each Project's files, terminals, and splits.",
    "閉じる前に確認": "Confirm before closing",
    "実行中のターミナルや未保存のエディタを閉じる前に確認します。": "Asks before closing running terminals or unsaved editors.",
    "インターフェース": "Interface",
    "外観": "Appearance",
    "エディタ、ターミナル、サイドバーの配色をまとめて切り替えます。": "Switches the colors of the editor, terminal, and sidebar together.",
    "言語": "Language",
    "ステータスバーの利用枠を隠す": "Hide usage quota in the status bar",
    "承認ポリシー": "Approval policy",
    "ターミナル・Agent会話での変更提案を、どこまで自動で通すか。": "How far changes proposed in terminals and agent chats go through automatically.",
    "表示": "Display",
    "文字サイズ": "Font size",
    "行番号を表示": "Show line numbers",
    "編集": "Editing",
    "保存時に整形": "Format on save",
    "⌘S のタイミングでフォーマッタを実行します。": "Runs the formatter on ⌘S.",
    "タブ幅": "Tab width",
    "空白文字を表示": "Show whitespace",
    "タブ・行末の空白を薄く可視化します。": "Faintly shows tabs and trailing spaces.",
    "行の折り返し": "Word wrap",
    "長い行をエディタの幅に合わせて折り返します。⌥Z でも切り替えられます。": "Wraps long lines to the editor width. ⌥Z also toggles it.",
    "拡張子の言語": "Languages by extension",
    "組み込みの判定より優先されます。開き直したファイルから反映されます。": "Overrides the built-in detection. Applies to files as they are reopened.",
    "拡張子": "Extension",
    "カーソルの形": "Cursor style",
    "カーソルを点滅": "Blink cursor",
    "シェルやアプリが形・点滅を指定したときはそちらが優先されます。": "A shape or blink set by the shell or app takes precedence.",
    "シェルと承認": "Shell and approvals",
    "デフォルトシェル": "Default shell",
    "コマンド実行前に確認": "Confirm before running commands",
    "agentが実行するコマンドの承認プロンプト。": "Approval prompt for commands an agent runs.",
    "スクロールバック": "Scrollback",
    "電源": "Power",
    "バッテリー駆動中もエージェント実行中はスリープさせない": "Prevent sleep on battery while agents run",
    "セッションの確認": "Check sessions",
    "同じネットワーク上の端末からセッションを確認します。": "Check sessions from devices on the same network.",
    "連携": "Integration",
    "clair コマンドをインストール": "Install the clair command",
    "インストール済み(%@)。": "Installed (%@).",
    "%@ にリンクし、ターミナルやAgentからClairを操作できるようにします。": "Links it at %@ so terminals and agents can drive Clair.",
    "再インストール": "Reinstall",
    "インストール": "Install",
    "アンインストール": "Uninstall",
    "インストールしました(%@)。": "Installed (%@).",
    "Agent skill をインストール": "Install the agent skills",
    "インストール済み(~/.claude/skills, ~/.agents/skills)。": "Installed (~/.claude/skills, ~/.agents/skills).",
    "clair-agents / clair-preview skill を ~/.claude/skills と ~/.agents/skills に置きます。": "Puts the clair-agents / clair-preview skills in ~/.claude/skills and ~/.agents/skills.",
    "インストールしました。": "Installed.",
    "インストールできません: %@": "Could not install: %@",
    "バージョン": "Version",
    "現在のバージョン": "Current version",
    "Dev ビルドは更新フィードを持ちません。": "Dev builds have no update feed.",
    "%@ が利用できます": "%@ is available",
    "更新を確認": "Check for updates",
    "確認": "Check",
    "フォント": "Font",
    "インストール済みの等幅フォントから選びます。": "Choose from installed monospaced fonts.",
    "システム等幅": "System monospaced",
    "既定のAgent": "Default agent",
    "⌃⌘N で追加するときの初期選択。titlebarのタブは個別に選べます。": "Preselected when adding with ⌃⌘N. Titlebar tabs can each pick their own.",
    "ターミナルのカーソルを点滅": "Blink terminal cursor",
    "エディタの文字サイズ": "Editor font size",
    "ターミナルの文字サイズ": "Terminal font size",
    "ターミナルのカーソルの形": "Terminal cursor style",
    "毎回確認": "Ask every time", "セッション中は許可": "Allow for session", "自動承認": "Auto-approve",
    "ダーク": "Dark", "ライト": "Light", "システム": "System",
    "ブロック": "Block", "バー": "Bar", "下線": "Underline",
    "オン": "on", "オフ": "off",
    "設定: %@を%@にする": "Settings: turn %1$@ %2$@",
    "設定: %@を %@ にする": "Settings: set %1$@ to %2$@",
    "設定を開く: %@": "Open Settings: %@",
    "設定を閉じる": "Close Settings",
    "チェンジログ": "Changelog",
    "設定を検索": "Search settings",
    "設定": "Settings",

    // Commands (registry titles)
    "ペインを右に分割": "Split Pane Right", "ペインを下に分割": "Split Pane Down", "ターミナルを開く": "Open Terminal",
    "ペインのフォーカスを右へ": "Focus Next Pane", "ペインのフォーカスを左へ": "Focus Previous Pane", "ペインにフォーカス": "Focus Pane",
    "ペインを最大化": "Maximize Pane", "分割を均等化": "Equalize Splits", "分割比を変更": "Change Split Ratio",
    "ペインを移動": "Move Pane", "ペインの表示を入れ替え": "Swap Panes", "ペインを閉じる": "Close Pane", "ペインを開く": "Open Pane",
    "エージェントを起動": "Launch Agent", "エージェントの状態": "Agent Status", "エージェントの出力": "Agent Output",
    "エージェントのペインを閉じる": "Close Agent Pane", "ファイルを開く": "Open File", "タブを切り替え": "Switch Tab",
    "次のタブ": "Next Tab", "前のタブ": "Previous Tab", "差分を開く": "Open Diff", "差分タブを切り替え": "Switch Diff Tab",
    "差分タブを閉じる": "Close Diff Tab", "閉じたタブを再度開く": "Reopen Closed Tab", "タブを並べ替え": "Reorder Tabs",
    "タブを移動": "Move Tab", "タブを閉じる": "Close Tab", "保存": "Save",
    "プロジェクトを切り替え": "Switch Project", "プロジェクトを閉じる": "Close Project", "プロジェクト名を変更": "Rename Project",
    "タブグループの色を変更": "Change Tab Group Color", "プロジェクトにフォルダを追加": "Add Folder to Project",
    "プロジェクトからフォルダを外す": "Remove Folder from Project", "タブグループを移動": "Move Tab Group",
    "フォルダをプロジェクトとして開く": "Open Folder as Project", "パスからファイルを開く": "Open File by Path",
    "HTML をプレビュー": "Preview HTML", "現在のファイルと選択範囲を取得": "Get Current File and Selection",
    "前の位置に戻る": "Go Back", "次の位置に進む": "Go Forward", "フォルダを開閉": "Toggle Folder", "設定を開く": "Open Settings",
    "clair コマンドをアンインストール": "Uninstall the clair Command", "Agent skill をアンインストール": "Uninstall the Agent Skills",
    "設定を変更": "Change Setting", "設定の選択肢を変更": "Change Setting Choice", "フォントを変更": "Change Font",
    "拡張子の言語を設定": "Set Languages by Extension", "サイドバーの表示切替": "Toggle Sidebar",
    "ウインドウを再起動": "Restart Window", "アプリを再起動": "Restart App", "コマンドパレット": "Command Palette",
    "ファイルへ移動": "Go to File", "Project を検索": "Find in Project", "検索": "Search",
    "Compare With…（アクティブファイルと比較）": "Compare With…", "Open Recent…（最近開いたファイル）": "Open Recent…",
    "パレットを閉じる": "Close Palette", "シンボルへ移動": "Go to Symbol", "参照一覧": "References",
    "行の折り返しを切り替え": "Toggle Word Wrap", "折りたたむ": "Collapse", "展開する": "Unfold", "すべて折りたたむ": "Fold All",
    "すべて展開する": "Unfold All", "定義へ移動": "Go to Definition", "プレビュー / 表で開く": "Open Preview / Table",
    "参照を検索": "Find References", "ドキュメントを整形": "Format Document", "通知を既読にする": "Mark Notifications Read",
    "通知履歴を消去": "Clear Notification History", "Project の通知をミュート": "Mute Project Notifications",
    "ターミナルの通知をミュート": "Mute Terminal Notifications", "実行とデバッグ": "Run and Debug",
    "Go をデバッグ起動": "Debug Go", "Go プロセスに接続": "Attach to Go Process", "ブレークポイントを切り替え": "Toggle Breakpoint",
    "デバッグスレッドを選択": "Select Debug Thread", "スタックフレームを選択": "Select Stack Frame", "変数を展開": "Expand Variable",
    "デバッグを続行": "Continue Debugging", "デバッグを一時停止": "Pause Debugging", "ステップオーバー": "Step Over",
    "ステップイン": "Step Into", "ステップアウト": "Step Out", "デバッグを再起動": "Restart Debugging", "デバッグを終了": "Stop Debugging",
    "状態を取得": "Get State", "ショートカットを割り当て": "Assign Shortcut",
    "読み取り": "read", "追加": "Add", "書き込み": "write", "破壊的": "destructive", "外部": "external",
    "%@ を起動": "Launch %@",

    // Command errors
    "最後の Project は閉じられません": "The last Project cannot be closed",
    "%@ に未保存の変更があります": "%@ has unsaved changes",
    "%@ は既にこの Project に含まれています": "%@ is already in this Project",
    "未保存の変更があります": "There are unsaved changes",
    "HTML ファイルを指定してください": "Specify an HTML file",
    "戻る位置がありません": "Nowhere to go back to",
    "進む位置がありません": "Nowhere to go forward to",
    "%@ に %@ は選べません": "%1$@ cannot be %2$@",
    "フォント名が不正です": "Invalid font name",
    "ファイルが開かれていません": "No file is open",
    "Markdown / CSV / HTML ファイルが開かれていません": "No Markdown / CSV / HTML file is open",
    "対応していないファイル形式です": "Unsupported file type",
    "Project が開かれていません": "No Project is open",
    "起動対象は Project 内にしてください": "The launch target must be inside the Project",
    "起動対象がありません: %@": "Launch target not found: %@",
    "デバッグセッションが既に実行中です": "A debug session is already running",
    "PID は正の整数にしてください": "PID must be a positive integer",
    "ファイルが Project 外です": "The file is outside the Project",
    "ファイルがありません: %@": "File not found: %@",
    "行は 1 以上にしてください": "Line must be 1 or greater",
    "停止中の session がありません": "No stopped session",
    "実行中の session がありません": "No running session",
    "再起動する session がありません": "No session to restart",
    "終了する session がありません": "No session to stop",
    "%@: Clair の状態が承認中に変わったため実行しませんでした": "%@: not run because Clair's state changed during approval",
    "%@: 承認時より危険度が上がったため実行しませんでした": "%@: not run because its risk rose after approval",

    // App shell
    "保存できません: %@": "Could not save: %@",
    "変更を保存してからアプリを再起動してください。": "Save your changes before restarting the app.",
    "アプリを再起動できませんでした": "Could not restart the app",
    "clair コマンド": "the clair command",
    "%@を%@しました。": "%2$@ed %1$@.",
    "%@を%@できません: %@": "Could not %2$@ %1$@: %3$@",
    "このファイルの言語サーバーはありません": "No language server for this file",
    "言語サーバーが応答しません": "The language server is not responding",
    "参照が見つかりません": "No references found",
    "定義が見つかりません": "No definition found",
    "Git Project ではありません。": "Not a Git Project.",
    "保存できません: ファイルを開けません。": "Could not save: the file cannot be opened.",
    "ドキュメントの整形": "Format Document",
    "%@ · ターミナル %@": "%@ · Terminal %@",
    "%@ · %@ · ターミナル %@ · %@": "%@ · %@ · Terminal %@ · %@",
    "デバッグを再起動しますか？": "Restart debugging?",
    "未保存の変更を破棄しますか？": "Discard unsaved changes?",
    "再起動": "Restart",
    "破棄して続行": "Discard and Continue",
    "フォルダを開く": "Open Folder",
    "ファイル、シンボル": "Files, symbols",
    "%@ タブグループを展開": "Expand the %@ tab group",
    "%@ タブグループを折りたたむ": "Collapse the %@ tab group",
    "%@ に切り替え": "Switch to %@",
    "コミットグラフ": "Commit Graph",
    "比較: %@ ↔ %@": "Compare: %@ ↔ %@",
    "差分: %@": "Diff: %@",
    "このProjectに切り替え": "Switch to This Project",
    "グループを展開": "Expand Group",
    "グループを折りたたむ": "Collapse Group",
    "フォルダを追加…": "Add Folder…",
    "Project名を変更…": "Rename Project…",
    "Project名を変更": "Rename Project",
    "空にするとフォルダ名に戻ります。": "Leave empty to use the folder name.",
    "左へ移動": "Move Left",
    "右へ移動": "Move Right",
    "通知のミュートを解除": "Unmute Notifications",
    "通知をミュート": "Mute Notifications",
    "Projectを閉じる": "Close Project",
    "閉じられませんでした": "Could not close",
    "追加できませんでした": "Could not add",
    "コミットグラフを開く": "Open Commit Graph",
    "検索中…": "Searching…",
    "検索中… %@ 件": "Searching… %@ results",
    "一致なし": "No results",
    "%@ 件 / %@ ファイル": "%@ results in %@ files",
    "正規表現が不正です": "Invalid regular expression",
    "検索できません: %@": "Could not search: %@",
    "置換中…": "Replacing…",
    "%@ 件を置換しました": "Replaced %@",
    "置換できません: %@": "Could not replace: %@",
    "Clair %@ が利用できます": "Clair %@ is available",
    "更新を適用しています": "Applying the update",
    "完了後に再起動します。": "Clair restarts when done.",
    "あとで": "Later",
    "適用して再起動": "Apply and Restart",
    "ステージ": "Stage",
    "ステージ解除": "Unstage",
    "変更を確認": "Review Changes",
    "ステージを取り消す": "Unstage",
    "ステージに追加": "Stage",
    "ファイルを削除…": "Delete File…",
    "変更を元に戻す…": "Discard Changes…",
    "一括ステージ": "Stage All",
    "一括ステージ解除": "Unstage All",
    "コミット": "Commit",
    "%@中…": "%@…",
    "%@中": "%@…",
    "%@ を削除しますか？": "Delete %@?",
    "%@ の変更を破棄しますか？": "Discard changes to %@?",
    "ステージ済みと未ステージの変更をすべて HEAD の状態に戻します。取り消せません。": "Resets staged and unstaged changes to HEAD. This cannot be undone.",
    "取り消せません。": "This cannot be undone.",
    "削除": "Delete",
    "破棄": "Discard",
    "変更の破棄": "Discard Changes",
    "%@が完了しました。": "%@ finished.",
    "この Project をレビュー": "Review This Project",
    "開く": "Open",
    "Project からフォルダを外す": "Remove Folder from Project",
    "外せませんでした": "Could not remove",
    "このフォルダをレビュー": "Review This Folder",
    "レビューを開始できませんでした": "Could not start the review",
    "分割して開く": "Open to the Side",
    "比較対象として選択": "Select for Compare",
    "%@ と比較": "Compare with %@",
    "このファイルをレビュー": "Review This File",
    "新しいファイル…": "New File…",
    "新しいフォルダー…": "New Folder…",
    "名前を変更…": "Rename…",
    "操作できませんでした": "Could not complete the operation",
    "新しいフォルダー": "New Folder",
    "新しいファイル": "New File",
    "名前を変更": "Rename",
    "“%@” を削除しますか?": "Delete “%@”?",
    "フォルダーとその中身をゴミ箱に移動します。": "Moves the folder and its contents to the Trash.",
    "ゴミ箱に移動します。": "Moves it to the Trash.",
    "ゴミ箱に移動": "Move to Trash",
    "Agent に送る": "Send to Agent",
    "パスをコピー": "Copy Path",
    "Finder で表示": "Reveal in Finder",
    "デバッグを開始": "Start Debugging",
    "Go: 現在のファイル": "Go: Current File",
    "Go: 現在の package をテスト": "Go: Test Current Package",
    "プロセスに attach": "Attach to Process",
    "Go: package テスト": "Go: Package Test",
    "デバッグ構成": "Debug configuration",
    "プロセス ID (PID)": "Process ID (PID)",
    "ブレークポイント": "Breakpoints",
    "ブレークポイントを削除": "Remove Breakpoint",
    "未検証": "Unverified",
    "検証済み": "Verified",
    "設定されていません": "None set",
    "スレッドとコールスタック": "Threads and Call Stack",
    "場所不明": "Unknown location",
    "停止すると表示されます": "Shown when stopped",
    "変数": "Variables",
    "デバッグコンソール": "Debug Console",
    "出力はありません": "No output",
    "Go ファイルを開き、構成を選んで開始してください。Delve (dlv) が必要です。": "Open a Go file, pick a configuration, and start. Requires Delve (dlv).",
    "構成を選んで開始してください。": "Pick a configuration and start.",
    "Delve に接続中…": "Connecting to Delve…",
    "ブレークポイントを設定中…": "Setting breakpoints…",
    "実行中 · %@": "Running · %@",
    "停止: %@": "Stopped: %@",
    "デバッグセッションは終了しました": "The debug session has ended",
    "続行": "Continue",
    "一時停止": "Pause",
    "終了": "Quit",
    "デバッグ操作": "Debug controls",
    "ファイルを開けません。": "Cannot open the file.",
    "差分を読み込み中…": "Loading diff…",
    "残り%@%": "%@% left",
    "利用枠を取得中…": "Loading quota…",
    "利用枠 —": "Quota —",
    "古い値 · %@ 取得": "Stale · fetched %@",
    "%@ 取得": "Fetched %@",
    "取得できません — %@": "Unavailable — %@",
    "未対応 — %@": "Unsupported — %@",
    "エラー %@": "%@ errors",
    "警告 %@": "%@ warnings",
    "通知": "Notifications",
    "通知 未読 %@ 件": "Notifications, %@ unread",
    "すべて既読": "Mark All Read",
    "消去": "Clear",
    "通知はありません": "No notifications",
    "ターミナル %@": "Terminal %@",
    "%@ · ターミナル %@ · %@": "%@ · Terminal %@ · %@",
    "ブランチを切り替え / 作成": "Switch / Create Branch",
    "%@ の同期: pull %@ 件 / push %@ 件\nクリックで Pull → Push": "Sync %@: pull %@ / push %@\nClick to Pull → Push",
    "同期 (Pull → Push)": "Sync (Pull → Push)",
    "未保存 %@": "%@ unsaved",
    "%@ セッション": "%@ sessions",
    " · 入力待ち %@": " · %@ waiting",
    "現在": "Current",
    "新しいブランチを作成: %@": "Create New Branch: %@",
    "%@ 件": "%@ items",
    "コマンド": "Commands",
    "ブランチ切替": "Branch switch",
    "ブランチ作成": "Branch creation",
    "準備中": "Coming soon",
    "閉じる": "Close",
    "パネルを閉じる": "Close Panel",
    "開いているペインはありません": "No open panes",
    "エディタを開く": "Open Editor",
    "⌘W でエディタを開けます": "⌘W opens an editor",
    "右に分割": "Split Right",
    "下に分割": "Split Down",
    "最大化": "Maximize",

    // Review
    "次のレビューコメントに対応してください。\n\n": "Address the following review comments.\n\n",
    "（コメント後に行が変更されています）": " (the line changed after the comment)",
    "バッファが変更されたため適用できません。": "Cannot apply because the buffer changed.",
    "適用できません。": "Cannot apply.",
    "コミットメッセージ": "Commit message",
    "変更はありません": "No changes",
    "ステージ済み": "Staged",
    "変更": "Changes",
    "未追跡": "Untracked",
    "%@ ファイル": "%@ files",
    "すべてステージに追加": "Stage All",
    "すべてステージから外す": "Unstage All",
    "ファイルを削除": "Delete File",
    "変更を元に戻す": "Discard Changes",
    "未追跡ファイル": "Untracked file",
    "index → 作業ツリー": "index → working tree",
    "差分": "Diff",
    "差分の表示に戻る": "Back to the diff",
    "このファイルを編集する": "Edit this file",
    "保存 ●": "Save ●",
    "このファイルを保存する": "Save this file",
    "インライン": "Inline",
    "並べて表示": "Side by Side",
    "差分を 1 列で表示": "Show the diff in one column",
    "変更前と変更後を左右に並べて表示": "Show before and after side by side",
    "全文脈": "Full Context",
    "変更箇所": "Changes Only",
    "ファイル全体を表示": "Show the whole file",
    "変更箇所に絞る": "Show only the changes",
    "前の hunk (⌥↑)": "Previous hunk (⌥↑)",
    "次の hunk (⌥↓)": "Next hunk (⌥↓)",
    "コピー済み（⌘V で貼り付け）": "Copied (paste with ⌘V)",
    "agent に送る": "Send to agent",
    "未解決コメントをプロンプトとしてコピーし、agent のターミナルへ移動": "Copy unresolved comments as a prompt and go to the agent's terminal",
    "差分はありません。": "No differences.",
    "この差分に表示できないコメント・提案": "Comments and suggestions that cannot be shown in this diff",
    "行が変更されたため位置を特定できません": "The line changed, so its position is unknown",
    "%@ 行目": "Line %@",
    "⋯ 変更のない %@ 行を表示": "⋯ Show %@ unchanged lines",
    "折りたたまれた行を展開": "Expand collapsed lines",
    "差分が長いため %@ 行で打ち切りました。": "The diff is long; cut off at %@ lines.",
    "クリックしてコメント": "Click to comment",
    "解決する": "Resolve",
    "解決済み": "Resolved",
    "提案 · %@ 行目": "Suggestion · line %@",
    "適用": "Apply",
    "却下": "Dismiss",
    "バッファが変更されたため適用できません": "Cannot apply because the buffer changed",
    "適用済み（未保存。⌘S で保存）": "Applied (unsaved; ⌘S to save)",
    "却下済み": "Dismissed",
    "一部適用済み": "Partly applied",
    "この行の置換後": "Replacement for this line",
    "コメント": "Comment",
    "提案する": "Suggest",
    "コメントに戻す": "Back to Comment",
    "提案にする": "Make a Suggestion",
    "キャンセル": "Cancel",
    "AI が実行を求めています": "AI wants to run a command",
    "残り %@ 秒": "%@ s left",
    "リスク %@": "Risk: %@",
    "拒否": "Deny",
    "許可して実行": "Allow and Run",
    "Projectを検索": "Find in Project",
    "%@件 · %@ファイル": "%@ results · %@ files",
    "正規表現": "Regular expression",
    "大文字小文字を区別": "Match case",
    "置換": "Replace",
    "すべて置換": "Replace All",
    "置換 ⌥⌘F": "Replace ⌥⌘F",
    "エージェント": "Agents",
    "起動中のエージェントはありません": "No running agents",
    "過去のチャット": "Past chats",
    "履歴を更新": "Refresh history",
    "履歴はありません": "No history",
    "アーカイブ（1ヶ月以上前）": "Archive (over a month ago)",
    "アーカイブはありません": "No archive",
    "%@ · %@ · %@ 件": "%@ · %@ · %@ prompts",
    "送信した依頼 %@ 件": "%@ prompts sent",
    "昨日": "Yesterday",
    "さらに表示（残り %@ 件）": "Show more (%@ left)",
    "依頼 %@ 件": "%@ prompts",
    "途中経過 %@ 件": "%@ progress steps",
    "推定 %@": "Est. %@",
    "ターミナルで再開": "Resume in Terminal",
    "このチャットのディレクトリを Project に追加すると再開できます": "Add this chat's directory to a Project to resume it",
    "%@ をターミナルで開き、このチャットを再開": "Open %@ in a terminal and resume this chat",
    "再開コマンドをコピー: %@": "Copy resume command: %@",
    "再開コマンドをコピー": "Copy Resume Command",
    "スキル読込": "Skill loaded",
    "続きを表示": "Show more",

    // Quota and usage
    "%@分間": "%@ min",
    "1か月": "1 mo", "%@日間": "%@ d", "%@時間": "%@ h",
    "まもなくリセット": "Resets soon",
    "リセットまで %@日%@時間": "Resets in %@d %@h",
    "リセットまで %@時間%@分": "Resets in %@h %@m",
    "リセットまで %@分": "Resets in %@m",
    "%@ 残り%@% · %@": "%@ %@% left · %@",
    "(古い値 · %@ 取得)": " (stale · fetched %@)",
    "(%@ 取得)": " (fetched %@)",
    "Claude Code にログインしていません": "Not logged in to Claude Code",
    "Claude Code のログインが期限切れです(claude を一度起動すると更新されます)": "The Claude Code login expired (running claude once refreshes it)",
    "api.anthropic.com に接続できません": "Cannot reach api.anthropic.com",
    "利用枠 API の呼び出し制限中です": "The quota API is rate limited",
    "api.anthropic.com が HTTP %@ を返しました": "api.anthropic.com returned HTTP %@",
    "このアカウントには利用枠の情報がありません": "This account has no quota information",
    "OpenCode Go にログインしていません(opencode auth login)": "Not logged in to OpenCode Go (opencode auth login)",
    "opencode.ai に接続できません": "Cannot reach opencode.ai",
    "opencode.ai が HTTP %@ を返しました": "opencode.ai returned HTTP %@",
    "Codex を起動できません": "Cannot start Codex",
    "Codex CLI が見つからないか応答しません": "The Codex CLI is missing or not responding",
    "取得に失敗しました": "Failed to fetch",
    "%@: %@ 件": "%@: %@",
    "依頼・追記: %@ 件": "Prompts and follow-ups: %@",
    "依頼・追記": "Prompts and follow-ups",
    "再集計": "Recount",
    "今日": "Today",
    "件": "",
    "直近7日": "Last 7 days",
    "直近100日": "Last 100 days",
    "費用の推定・全期間": "Estimated cost, all time",
    "日別アクティビティ": "Daily activity",
    "直近100日 · 1マス = 1日 · 右端が最新": "Last 100 days · 1 cell = 1 day · newest on the right",
    "エージェント別": "By agent",
    "依頼・追記 / 推定費用": "Prompts / estimated cost",

    // Git
    "git が %@ 秒以内に終わらなかったため中断しました。\n%@": "git did not finish within %@ seconds and was stopped.\n%@",
    "Git から詳細が返りませんでした。": "Git returned no details.",
    "認証が必要です。ターミナルで Git の認証を設定してください。\n%@": "Authentication required. Set up Git authentication in a terminal.\n%@",
    "%@ に失敗しました。\n%@": "%@ failed.\n%@",
    "変更をステージ": "Stage Changes",
    "ステージを解除": "Unstage",
    "変更を破棄": "Discard Changes",
    "ブランチを切り替え": "Switch Branch",
    "未保存のファイルを保存してから切り替えてください": "Save unsaved files before switching",
    "ブランチを作成": "Create Branch",
    "ブランチを切り替え…": "Switch Branch…",
    "detached HEAD では pull できません": "Cannot pull on a detached HEAD",
    "upstream が設定されていません": "No upstream is set",
    "未保存のファイルを保存してから pull してください": "Save unsaved files before pulling",
    "detached HEAD では push できません": "Cannot push on a detached HEAD",
    "ブランチを削除": "Delete Branch",
    "ブランチ全体をレビュー": "Review the Whole Branch",
    "worktree を作成": "Create Worktree",
    "worktree をマージ": "Merge Worktree",
    "worktree を削除": "Delete Worktree",
    "Git リポジトリではありません。": "Not a Git repository.",
    "コミットがありません": "No commits",
    "グラフに戻る": "Back to Graph",

    // Previews and tables
    "Markdown ファイルを開くとプレビューを表示します。": "Open a Markdown file to see its preview.",
    "上に行を挿入": "Insert Row Above",
    "下に行を挿入": "Insert Row Below",
    "行を削除": "Delete Row",
    "左に列を挿入": "Insert Column Left",
    "右に列を挿入": "Insert Column Right",
    "列を削除": "Delete Column",
    "%@ 行 × %@ 列": "%@ rows × %@ columns",
    "行を追加": "Add Row",
    "列を追加": "Add Column",
    "CSV / TSV ファイルを開くと表で編集できます。": "Open a CSV / TSV file to edit it as a table.",
    "表の編集": "Table editor",
    "HTML プレビュー": "HTML preview",
    "HTML ファイルを開くとプレビューを表示します。": "Open an HTML file to see its preview.",
    "縮小": "Zoom Out",
    "拡大": "Zoom In",
    "元のサイズに戻す": "Actual Size",

    // Debugger
    "未対応の起動モードです": "Unsupported launch mode",
    "起動対象は Project 内の既存ファイルまたはフォルダを選んでください": "Pick an existing file or folder inside the Project to launch",
    "ブレークポイントを設定できません: %@": "Could not set breakpoints: %@",
    "検証されませんでした": "not verified",
    "ブレークポイント %@:%@: %@": "Breakpoint %@:%@: %@",
    "デバッグ操作 %@ に失敗: %@": "Debug action %@ failed: %@",
    "デバッグセッションを終了しました": "Debug session ended",
    "例外で停止しました": "Stopped on an exception",
    "デバッグ情報を取得できません: %@": "Could not get debug info: %@",
    "デバッガーとの接続が終了しました": "The debugger connection closed",
    "デバッガーの応答が不正です: %@": "Invalid debugger response: %@",
    "要求": "the request",
    "デバッガーが %@ を拒否しました": "The debugger rejected %@",

    // Editor pane
    "ファイルを読み込めません。": "Cannot read the file.",
    "%@ MiB を超えるファイルは開けません。": "Files over %@ MiB cannot be opened.",
    "UTF-8 のテキストではないため開けません。": "Cannot open: not UTF-8 text.",
    "プレビューを開く (⌘⇧V)": "Open Preview (⌘⇧V)",
    "プレビューを開く": "Open Preview",
    "ファイルを選択してください。": "Select a file.",
    "表で編集 (⌘⇧V)": "Edit as Table (⌘⇧V)",
    "表エディタを開く": "Open Table Editor",
    "分割を閉じる (⌘W)": "Close Split (⌘W)",
    "分割を閉じる": "Close Split",
    "補完候補": "Completions",

    // Agent review request
    "%@\nコードを変更せず、正しさ・データ損失・セキュリティ・回帰の問題を探してください。": "%@\nWithout changing code, look for correctness, data-loss, security, and regression problems.",
    "指摘は重要度順に、ファイルと行、再現条件、理由を具体的に報告してください。": "Report findings by severity, with the file and line, how to reproduce, and why.",
    "問題が見つからなければ、その旨と確認した範囲を報告してください。": "If you find nothing, say so and report what you checked.",

    // CLI install, colors, app lifecycle, misc
    "clair 実行ファイルがアプリ内に見つかりません。": "The clair executable is missing from the app.",
    "%@ に別のファイルがあります。削除してから再試行してください。": "Another file exists at %@. Remove it and try again.",
    "インストールを中止しました。": "Installation stopped.",
    "%@ はこの Clair のリンクではないため削除しません。": "%@ is not this Clair's link, so it was left in place.",
    "アンインストールを中止しました。": "Uninstallation stopped.",
    "色を変更": "Change Color",
    "カラーピッカーを閉じる": "Close color picker",
    "カラーピッカーを開く": "Open color picker",
    "彩度と明るさ": "Saturation and brightness",
    "色相": "Hue",
    "Clair を終了しますか？": "Quit Clair?",
    "実行中のターミナルとエージェントも終了します。": "Running terminals and agents will also stop.",
    "前回 Clair がクラッシュしました": "Clair crashed last time",
    "%@ のクラッシュレポートから GitHub issue を作成しますか？ブラウザで内容を確認してから送信できます。": "Create a GitHub issue from the %@ crash report? You can review it in the browser before sending.",
    "issue を作成": "Create Issue",
    "不明": "Unknown",
    "チャット": "Chat",
    "%@ 未インストール": "%@ not installed",
    "%@ 起動中…": "Starting %@…",
    "%@ 停止": "%@ stopped",
    "テスト通知": "Test notification",
    "通知は正しく届いています。": "Notifications are working.",
    "macOS 通知": "macOS notifications",
    "通知を有効にする": "Enable notifications",
    "Clair の terminal で動く agent の通知要求と終了を macOS に送ります。": "Sends notification requests and exits of agents in Clair terminals to macOS.",
    "入力待ち・通知要求で通知": "Notify when waiting for input or asked to",
    "終了で通知": "Notify on exit",
    "正常終了・異常終了のどちらも対象です。": "Both successful and failed exits.",
    "Clair が前面のときも通知": "Notify while Clair is in front",
    "オフのときは他のアプリを使っている間だけ通知します。": "When off, notifies only while you use another app.",
    "サウンドを鳴らす": "Play a sound",
    "テスト": "Test",
    "テスト通知を送る": "Send a test notification",
    "macOS の通知許可と表示を確認します。": "Checks macOS notification permission and display.",
    "送信": "Send",
    "送信しました。表示されない場合は システム設定 → 通知 → Clair を確認してください。": "Sent. If nothing appears, check System Settings → Notifications → Clair.",
    "送信できませんでした。システム設定 → 通知 → Clair で許可してください（アプリ bundle 以外では動きません）。": "Could not send. Allow it in System Settings → Notifications → Clair (works only from the app bundle).",
    "通知のサウンド": "Notification sound",
    "最新の状態です。": "Clair is up to date.",
    "確認中…": "Checking…",
    "更新を適用しています。完了後に再起動します。": "Applying the update. Clair restarts when done.",
    "実行中": "Running",
    "入力待ち（ベル）": "Waiting for input (bell)",
    "%@: 取得できません — %@": "%@: unavailable — %@",
    "%@: 未対応 — %@": "%@: unsupported — %@",
    "Claude Code の認証に失敗しました(%@)": "Claude Code authentication failed (%@)",
    "OpenCode Go の認証に失敗しました(%@)": "OpenCode Go authentication failed (%@)",
    "Delve (dlv) が見つかりません。go install github.com/go-delve/delve/cmd/dlv@latest で導入してください。": "Delve (dlv) not found. Install it with go install github.com/go-delve/delve/cmd/dlv@latest.",
    "デバッガーに接続できませんでした": "Could not connect to the debugger",
    "デバッガーの応答がありません: %@": "No response from the debugger: %@",
    "終了コード: %@": "Exit code: %@",
    "Project 内のファイル `%@` をレビューしてください。": "Review the file `%@` in the Project.",
    "Project 内のフォルダ `%@/` 配下をレビューしてください。": "Review everything under the folder `%@/` in the Project.",
    "この Project 全体をレビューしてください。変更中のファイルだけでなく、関連する実装も確認してください。": "Review this whole Project. Check the related implementation, not only the files being changed.",
    "正常終了": "Exited",
    "異常終了 (exit %@)": "Failed (exit %@)",
  ]

  static let japanese: [String: String] = [
    // Menu bar titles (ClairAppShell `titles`)
    "Settings…": "設定…", "Save": "保存", "Reopen Closed Tab": "閉じたタブを再度開く",
    "Close Tab or Pane": "タブまたはペインを閉じる", "Open Recent…": "最近開いたファイル…", "Compare With…": "比較…",
    "Restart Window": "ウインドウを再起動", "Restart App": "アプリを再起動", "Find": "検索", "Find in Project": "Project を検索",
    "Format Document": "ドキュメントを整形", "Fold": "折りたたむ", "Unfold": "展開する", "Fold All": "すべて折りたたむ",
    "Unfold All": "すべて展開する", "Toggle Sidebar": "サイドバーの表示切替", "Command Palette": "コマンドパレット",
    "Split Right": "右に分割", "Split Down": "下に分割", "Maximize Pane": "ペインを最大化", "Equalize Panes": "分割を均等化",
    "Show Terminal": "ターミナルを開く", "Toggle Word Wrap": "行の折り返しを切り替え", "Open Preview": "プレビューを開く",
    "Go to Definition": "定義へ移動", "Find References": "参照を検索", "Go Back": "前の位置に戻る", "Go Forward": "次の位置に進む",
    "Go to File…": "ファイルへ移動…", "Go to Symbol…": "シンボルへ移動…", "Find References…": "参照一覧…",
    "Next Tab": "次のタブ", "Previous Tab": "前のタブ", "Focus Next Pane": "次のペインにフォーカス",
    "Focus Previous Pane": "前のペインにフォーカス",
    "Pane": "ペイン",
  ]
}
